# Generated by Django 2.1.3 on 2018-11-30 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=20)),
                ('url', models.CharField(max_length=500)),
                ('picture', models.CharField(max_length=300)),
                ('source', models.CharField(max_length=20)),
                ('time', models.DateTimeField()),
            ],
        ),
    ]
