# Generated by Django 2.1.3 on 2018-12-04 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20181130_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='url',
            field=models.CharField(max_length=1000),
        ),
    ]
